//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviewWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string Movie { get; set; }
        public string user_email { get; set; }
        public string Review1 { get; set; }
        public int Id { get; set; }
    
        public virtual Movie Movie1 { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
